# Generated by Django 4.1 on 2022-09-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isitodolist',
            old_name='date',
            new_name='todo_date',
        ),
        migrations.RenameField(
            model_name='isitodolist',
            old_name='description',
            new_name='todo_description',
        ),
        migrations.RenameField(
            model_name='isitodolist',
            old_name='title',
            new_name='todo_title',
        ),
    ]
