# Generated by Django 4.1 on 2022-09-27 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_rename_date_isitodolist_todo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isitodolist',
            name='todo_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='isitodolist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_todo', to=settings.AUTH_USER_MODEL),
        ),
    ]
