# Generated by Django 4.1 on 2022-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_isitodolist_todo_date_alter_isitodolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isitodolist',
            name='todo_date',
            field=models.TextField(),
        ),
    ]
