# Generated by Django 4.1 on 2022-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_isitodolist_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='isitodolist',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
