# Generated by Django 4.1 on 2022-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_watched', models.BooleanField(max_length=50)),
                ('film_title', models.TextField()),
                ('film_rating', models.IntegerField()),
                ('film_release', models.TextField()),
                ('film_review', models.TextField()),
            ],
        ),
    ]
